### ISSUE TITLE
出现：SyntaxError: Unexpected token function怎么解决？

### ISSUE THREAD

**Issue by huos3203** [zhougy0717/zhougy0717.github.io#9]
```
$ DEBUG=* everblog build
/usr/local/lib/node_modules/everblog/bin/everblog:55
async function showConfig () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by zhougy0717** [comment]
你什么系统啊，运行的什么命令。看起来你没用node

布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午12:19写道：

**Comment by huos3203** [comment]
升级node之后，解决了。
目前还有问题：
$ DEBUG=* everblog build
```
  everblog getNotebook -> hexo +0ms
(node:32512) UnhandledPromiseRejectionWarning: #<ThriftException>
(node:32512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
怎么知道成功了？build是将印象笔记的下载到本地的source目录了吗
[everbolg issues](https://github.com/everblogjs/everblog/issues/11#issuecomment-431245377)

**Comment by zhougy0717** [comment]
会在public目录下生成post,然后如果用hexo,hexo d就可以部署了

布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午5:06写道：

**Comment by zhougy0717** [comment]
你这个是又发生crash了，你用的哪个adapter?

布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午5:06写道：

**Comment by huos3203** [comment]
> 你这个是又发生crash了，你用的哪个adapter? 布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午5:06写道：
> […](#)

everblog-adaptor-hexo

**Comment by zhougy0717** [comment]
那你要自己调试看看，或者你用我fork的版本+everblog-adaptor-hexo-html 。这个我一直在用，没有问题(有问题fix掉了)

布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午7:01写道：

**Comment by huos3203** [comment]
> 那你要自己调试看看，或者你用我fork的版本+everblog-adaptor-hexo-html 。这个我一直在用，没有问题(有问题fix掉了) 布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午7:01写道：
> […](#)

npm i everblog-adaptor-hexo-html --save
刚试了下，配置index.js 运行build还是存在

**Comment by huos3203** [comment]
> 那你要自己调试看看，或者你用我fork的版本+everblog-adaptor-hexo-html 。这个我一直在用，没有问题(有问题fix掉了) 布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午7:01写道：
> […](#)
(node:32512) UnhandledPromiseRejectionWarning: #<ThriftException>
这种情况，是token导致的吗？用的是国际版还是国内的token？

**Comment by zhougy0717** [comment]
这个情况就是你程序crash,但源代码没做良好的错误处理来显示error code。国内版国际版搞错是有可能的，具体你可以看我的博客
https://zhougy0717.github.io/2017/07/03/在GitHub上用Evernote+Hexo搭建个人静态博客/

布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午7:07写道：

**Comment by huos3203** [comment]
> 这个情况就是你程序crash,但源代码没做良好的错误处理来显示error code。国内版国际版搞错是有可能的，具体你可以看我的博客 [https://zhougy0717.github.io/2017/07/03/在GitHub上用Evernote+Hexo搭建个人静态博客/](https://zhougy0717.github.io/2017/07/03/%E5%9C%A8GitHub%E4%B8%8A%E7%94%A8Evernote+Hexo%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2/) 布衣男儿 <notifications@github.com> 于 2018年10月19日周五 下午7:07写道：
> […](#)

谢谢，正在尝试申请国际版tokon
